name: Build AWCC

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            build-essential \
            cmake \
            ninja-build \
            git \
            pkg-config \
            libsystemd-dev \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libxxf86vm-dev \
            libxkbcommon-dev \
            wayland-protocols \
            qt6-base-dev \
            qt6-tools-dev

      - name: Configure
        run: cmake -B build -G Ninja

      - name: Build
        run: cmake --build build --parallel

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: awcc
          path: build
